---

- name: Download Kafka chart and decompress
  ansible.builtin.unarchive:
    src: "{{ kafka_chart_tarball }}"
    dest: /tmp
    remote_src: true

- name: Install Kafka chart
  block:
    - name: Install Kafka chart
      ansible.builtin.shell:
        cmd: |
          helm upgrade --install {{ kafka_release_name }} /tmp/{{ (kafka_chart_tarball.split('/') | last).split('.') | first }} \
            --set global.namespace={{ kafka_namespace }} \
            --set global.kafka.enabled={{ kafka_enabled }} \
            --set global.kafka.replicas={{ kafka_replicas }} \
            --set global.kafka.ports.public_client={{ kafka_enable_public_connections | ternary(kafka_public_port, false) }} \
            --set global.kafka.public_ips="{{ '{' + kafka_public_ips + '}' }}" \
            --set global.zookeeper.enabled={{ (zookeeper_replicas > 0) | bool }} \
            --set global.zookeeper.replicas={{ zookeeper_replicas }} \
            --set global.zookeeper.ports.public_client={{ zookeeper_enable_public_connections | ternary(zookeeper_public_port, false) }} \
            --set global.kafka-ui.enabled="{{ kafka_ui_enabled }}" \
            --set global.kafka-ui.ports.public_client=30080
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: kafka_chart_install
      changed_when: >
        kafka_chart_install.rc == 0
      failed_when: >
        kafka_chart_install.rc != 0
      ignore_errors: true
    - name: Show result of installing Kafka chart
      ansible.builtin.debug:
        var: kafka_chart_install

- name: Fail if Kafka chart has not been installed
  block:
    - name: Get status of Kafka chart release
      ansible.builtin.command: helm status {{ kafka_release_name }}
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: kafka_chart_status
      changed_when: false
      ignore_errors: true # { "rc": 1, "stderr": "Error: release: not found" }
    - name: Show Kafka chart status
      ansible.builtin.debug:
        var: kafka_chart_status
    - name: Fail if Kafka chart has not been installed
      ansible.builtin.fail:
        msg: Error installing Kafka chart
      when: >
        ('STATUS: deployed' not in kafka_chart_status.stdout)
