---

# https://docs.confluent.io/platform/current/installation/docker/operations/external-volumes.html#data-volumes-for-ak-in-zk-mode
- name: Create Kafka persistent local volume
  block:
    - name: Empty Kafka persistent local volume
      ansible.builtin.file:
        path: /mnt/kafka
        state: absent
    - name: Create Kafka persistent local volume
      ansible.builtin.file:
        path: /mnt/kafka
        state: directory
        mode: '0755'
        owner: '1000'
        group: '1000'
